name: Regenerate Data
on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:
jobs:
  Regenerate-Data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile
      - run: |
        echo $AIRTABLE_BASE_ID
        env:
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      - run: yarn generate-data
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      - run: yarn process-data
      - uses: stefanzweifel/git-auto-commit-action@v4
